### PR TITLE
ISSUE_46

### LINKED ISSUE #46: 3DS verifyEnrollment broken in 4.59.0
You added a lot of function calls in the `verifyEnrollment` method, but those function now requires an array as first parameter. This is a breaking change.

https://github.com/PaylineByMonext/payline-php-sdk/compare/4.55.3...4.59.0#diff-eec0d48cf2eda6e48bad70276112f445R1776-R1781

According to [your documentation](https://payline.atlassian.net/wiki/spaces/DT/pages/1421377779/Webservice+-+verifyEnrollmentRequest), only the `order` is required for version 21

### PR DESCRIPTION
**Pull request by CharlelieBouvier**
- Other objects to check

fixes #46

### CODE REVIEW

File: src/Payline/PaylineSDK.php [hunk 1]
```diff
@@ -1763,7 +1765,10 @@ public function disablePaymentRecord(array $array)
     public function verifyEnrollment(array $array)
     {
         $this->formatRequest($array);
-        $order = $array['order'] != null ? $this->order($array['order']) : null;
+        $order = array_key_exists('order', $array) ? $this->order($array['order']) : null;
+        $buyer = array_key_exists('buyer', $array) ? $this->buyer($array['buyer'], $array['shippingAddress'], $array['billingAddress'], $array['merchantAuthentication']) : null;
+        $subMerchant = array_key_exists('subMerchant', $array) ? $this->subMerchant($array['subMerchant']) : null;
+        $threeDSInfo = array_key_exists('threeDSInfo', $array) ? $this->threeDSInfo($array['threeDSInfo'], $array['browser'], $array['sdk']) : null;
```
Comment (jdeniau) [inline src/Payline/PaylineSDK.php]: The `threeDSInfo` method signature does require arrays too for `browser` and `sdk`.

I do not know where this key comes from but you may have the same problem here too :|

Otherwise, it's seems OK

Comment (CharlelieBouvier) [reply src/Payline/PaylineSDK.php]: Well it is done the same way for the buyer with addresses, I'll try and let you know

Comment (CharlelieBouvier) [reply src/Payline/PaylineSDK.php]: The arrays are initiated in the \Payline\PaylineSDK::formatRequest function
